import swaggerAutogen from "swagger-autogen";

const doc = {
  info: {
    title: "Enterprise SaaS API",
    description: "API Documentation automatically generated by swagger-autogen",
    version: "1.8.1",
  },
  // host: "localhost:8000",
  basePath: "/api/v1",
  // schemes: ["http"],
  securityDefinitions: {
    bearerAuth: {
      type: "apiKey",
      name: "Authorization",
      in: "header",
      description: "Enter your JWT token in the format 'Bearer <token>'",
    },
  },
  security: [
    {
      bearerAuth: [],
    },
  ],
};

const outputFile = "./src/swagger_output.json"; // 👈 Where to save the generated file
const endpointsFiles = ["./src/app.ts"]; // 👈 The entry point to scan all routes

// Run the generator
swaggerAutogen()(outputFile, endpointsFiles, doc).then(() => {
  console.log("✅ Swagger documentation generated successfully!");
  process.exit(0);
});