import swaggerAutogen from "swagger-autogen";
import fs from "fs";

const doc = {
  info: {
    title: "Enterprise SaaS API",
    description: "API Documentation automatically generated by swagger-autogen",
    version: "1.8.1",
  },
  // host: "localhost:8000",
  basePath: "/",
  // schemes: ["http"],
  securityDefinitions: {
    bearerAuth: {
      type: "apiKey",
      name: "Authorization",
      in: "header",
      description: "Enter your JWT token in the format 'Bearer <token>'",
    },
  },
  security: [
    {
      bearerAuth: [],
    },
  ],
};

const outputFile = "./src/swagger_output.json"; // 👈 Where to save the generated file
const endpointsFiles = ["./src/app.ts"]; // 👈 The entry point to scan all routes

// Run the generator
swaggerAutogen()(outputFile, endpointsFiles, doc).then(() => {
  // 🛠️ ROOT FIX: Manually remove 'host' and 'schemes' to allow dynamic resolution
  // This overcomes the library's default behavior of inserting "localhost:3000"
  try {
    const swaggerFileContent = fs.readFileSync(outputFile, "utf-8");
    const swaggerJson = JSON.parse(swaggerFileContent);

    delete swaggerJson.host;
    delete swaggerJson.schemes;

    fs.writeFileSync(outputFile, JSON.stringify(swaggerJson, null, 2));
    console.log("✅ Swagger documentation generated successfully (Dynamic Host)!");
  } catch (err) {
    console.error("❌ Failed to post-process swagger file:", err);
    process.exit(1);
  }
  
  process.exit(0);
});